function [Possibility, CraneType]=EKCraneGiveTimeGetPossibility(model, ...
    MachineNumber, SplitCounter, CellularCraneMatrix, ... 
    JobNumber, StartTimeJob, FinishTimeJob, PreviousJobNumber, ... 
    FinishTimePreviousJobNumber, DayCount)

    

end